### PR TITLE
Minimum PHP version 5.5.9

### PR DESCRIPTION
**Pull request by Zarganwar**
Symfony bundles require it

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Can you provide more details please? I have no problem to merge it because it's just an example project, but I am interested in the reason for this PR... :)

**Comment by Zarganwar** [comment]
Here it is :-/
image

**Comment by mrtnzlml** [comment]
Oh, ok - can you update this line as well please? https://github.com/mrtnzlml/CMS-lite/blob/master/composer.json#L11

**Comment by Zarganwar** [comment]
Updated

**Comment by mrtnzlml** [comment]
Thank you.

**Pull request merged**
